name: "Hello World"

on:
  push:
    paths:
      - 'hello-world-docker-action/**'
      - '!hello-world-docker-action/Readme.md'
      - '.github/workflows/hello-world-docker-action.yml'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: fbigun/actions/hello-world-docker-action
      with:
        who-to-greet: 'Mona the Octocat'
    # 使用来自 `hello` 步骤的输出
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
