name: "Uploader for Onedrive"

on:
  push:
    paths:
    - 'uploader-onedrive/**'
    - '!uploader-onedrive/Readme.md'
    - '.github/workflows/uploader-onedrive.yml'

jobs:
  upload_to_onedrive:
    runs-on: ubuntu-latest
    name: Upload to Onedrive
    steps:
    - uses: actions/checkout@v2
    - name: uploader action step
      id: uploader
      uses: fbigun/actions/uploader-onedrive@master
      with:
        auth: '${{ secrets.ONEDRIVE_TOKEN }}'
        file-path: 'Readme.md'

    - name: Get the output time
      run: echo "upload result: ${{ steps.uploader.outputs.result }}"
